### ISSUE TITLE
The csv file with all foods and calories

### ISSUE THREAD

**Issue by satenikmnatsakanyan-aua** [LidaHak/calorie_calculator#1]
@LidaHak where is the list of food items - the csv file you had in the beginning?

**Comment by LidaHak** [comment]
> @LidaHak where is the list of food items - the csv file you had in the beginning?

That file is in my pycharm. I will upload csv as soon as I figure out how to use it. Maybe, I will use other data, I do not know yet. I am still working in that direction.
